
services:
  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dolibarr
      MYSQL_USER: doli
      MYSQL_PASSWORD: doli
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot"]
      interval: 5s
      timeout: 3s
      retries: 20

  dolibarr:
    image: dolibarr/dolibarr:22.0.1
    depends_on:
      db:
        condition: service_healthy
    ports: ["8080:80"]
    environment:
      DOLI_DB_HOST: db
      DOLI_DB_NAME: dolibarr
      DOLI_DB_USER: doli
      DOLI_DB_PASSWORD: doli
      DOLI_INSTALL_AUTO: "1"
      DOLI_URL_ROOT: "http://host.docker.internal:8080"
      DOLI_ADMIN_LOGIN: "admin"
      DOLI_ADMIN_PASSWORD: "admin"
      DOLI_MODULES: "societe,product,stock,bom,variants,propal,facture"
    volumes:
      - ./dolibarr-custom:/var/www/html/custom
      - shared_allure_report:/var/www/html/custom/qa/reports
    healthcheck:
      test: ["CMD-SHELL", "php -r 'exit(@fsockopen(\"127.0.0.1\", 80) ? 0 : 1);'"]
      interval: 10s
      timeout: 5s
      retries: 20

  e2e:
    build:
      context: .
      dockerfile: docker/e2e/Dockerfile
    working_dir: /work
    depends_on:
      dolibarr:
        condition: service_healthy
    environment:
      BASE_URL: "http://dolibarr:80"
      DOLI_USER: "admin"
      DOLI_PASS: "admin"
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
    volumes:
      - ./e2e:/work
      - allure_results:/work/report/allure-results
      - shared_allure_report:/work/report/allure-report
    command: ["sleep", "infinity"]

  allure:
    image: frankescobar/allure-docker-service
    ports: ["5050:5050"]
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 2
    volumes:
      - allure_results:/app/allure-results
      - shared_allure_report:/app/default-reports

  allure-ui:
    image: frankescobar/allure-docker-service-ui
    container_name: allure_ui
    ports:
      - "5252:5252"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: http://localhost:5050
    depends_on:
      - allure
    restart: always     

volumes:
  db_data:
  shared_allure_report:
  allure_results:
