
services:
  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dolibarr
      MYSQL_USER: doli
      MYSQL_PASSWORD: doli
    volumes:
      - db_data:/var/lib/mysql

  dolibarr:
    image: tuxgasy/dolibarr:latest
    depends_on: [db]
    ports: ["8080:80"]
    environment:
      DOLI_DB_HOST: db
      DOLI_DB_NAME: dolibarr
      DOLI_DB_USER: doli
      DOLI_DB_PASSWORD: doli
      DOLI_INSTALL_AUTO: "1"
      DOLI_URL_ROOT: "http://host.docker.internal:8080"
      DOLI_ADMIN_LOGIN: "admin"
      DOLI_ADMIN_PASSWORD: "admin"
      DOLI_MODULES: "societe"
    volumes:
      - ./dolibarr-custom:/var/www/html/custom
      - shared_allure_report:/var/www/html/custom/qa/reports

  e2e:
    image: mcr.microsoft.com/playwright:v1.56.0-jammy
    working_dir: /work
    depends_on: [dolibarr]
    environment:
      BASE_URL: "http://dolibarr:80"
      DOLI_USER: "admin"
      DOLI_PASS: "admin"
    volumes:
      - ./e2e:/work
      - allure_results:/work/report/allure-results
      - shared_allure_report:/work/report/allure-report
    command: |
      bash -c "
        apt-get update &&
        apt-get install -y openjdk-11-jdk &&
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 &&
        export PATH=$$PATH:$$JAVA_HOME/bin &&
        tail -f /dev/null
      "

  allure:
    image: frankescobar/allure-docker-service
    ports: ["5050:5050"]
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 2
    volumes:
      - allure_results:/app/allure-results
      - shared_allure_report:/app/default-reports

  allure-ui:
    image: frankescobar/allure-docker-service-ui
    container_name: allure_ui
    ports:
      - "5252:5252"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: http://localhost:5050
    depends_on:
      - allure
    restart: always     

volumes:
  db_data:
  shared_allure_report:
  allure_results:
